spring:
  datasource:
    write:
      jdbc-url: jdbc:postgresql://primary-db:5432/app_db
      username: app
      password: app_pass
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 5
        idle-timeout: 300000
    read:
      jdbc-url: jdbc:postgresql://replica-db:5432/app_db
      username: app
      password: app_pass
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 5
        idle-timeout: 300000
  jpa:
    show-sql: true