spring:
  datasource:
    write:
      url: jdbc:postgresql://localhost:5432/postgres   # <-- was jdbc-url
      username: user
      password: password
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 5
        idle-timeout: 300000
        read-only: false
    read:
      url: jdbc:postgresql://localhost:5433/postgres    # <-- was jdbc-url
      username: user
      password: password
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 10
        minimum-idle: 5
        idle-timeout: 300000
        read-only: true
  jpa:
    show-sql: true
